import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { BarChartComponent } from "../_components/bar-chart"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { BarChartBetter } from "../_components/bar-chart-better"

export default async function Dashboard() {
  return (
    <div className='flex flex-col justify-center items-start flex-wrap px-4 pt-4 gap-4'>
      <Card className='w-[20rem]'>
        <CardHeader className='flex flex-row items-center justify-between space-y-0 pb-2'>
          <CardTitle className='text-sm font-medium'>
            Total leads in last 30 days
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className='text-2xl font-bold'>30</div>
        </CardContent>
      </Card>
      <div className='flex flex-wrap gap-2'>
        <BarChartComponent />
        <BarChartBetter />
      </div>
      {/* <div className='grid md:grid-cols-2 sm:grid-cols-1 w-full gap-3'>
        <Card className=''>
          <CardHeader className='flex flex-row items-center'>
            <div className='grid gap-2'>
              <CardTitle>Latest Projects</CardTitle>
              <CardDescription>
                Recent projects generated by Nextjs Starter Kit
              </CardDescription>
            </div>
            <Button asChild className='ml-auto gap-1'>
              <Link href='/dashboard/projects'>View All</Link>
            </Button>
          </CardHeader>
          <CardContent>
            <div style={{ maxHeight: "320px", overflowY: "auto" }}>
              {" "}
             
              <main className='flex flex-col gap-2 lg:gap-2 h-[300px] w-full'>
                <div className='flex flex-1 items-center justify-center rounded-lg border border-dashed shadow-sm'>
                  <div className='flex flex-col items-center text-center'>
                    <h1 className='text-xl font-bold tracking-tight'>
                      You have no projects
                    </h1>
                    <p className='text-sm text-muted-foreground mb-3'>
                      Projects will show when you start using Nextjs Starter Kit
                    </p>
                  </div>
                </div>
              </main>
            </div>
          </CardContent>
        </Card>
      </div> */}
    </div>
  )
}
